arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: arm_jr_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.50000000000000001
  kinematics_solver_timeout: 3.00000000000000001
  kinematics_solver_attempts: 300
  position_only_ik: True
